name: Deploy to Server

on:
  push:
    branches:
      - master # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECONDSERVERKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 35.154.105.82 >> ~/.ssh/known_hosts
        env:
          MYSECRETKEY1: ${{ secrets.SECONDSERVERKEY }}

      - name: Install Dependencies and Build
        run: |
          # Install dependencies and build your React app
          npm install
          npm run build

      - name: Deploy Build to Server
        run: |
          # Copy the build artifacts to the server using SCP
          scp -r ./build/* ubuntu@35.154.105.82:/home/ubuntu/AutomaticDeploy
