name: My Deployment Workflow

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.6.0  # Change to your desired Node.js version

    - name: Install dependencies
      run: npm ci --only=production  # Install production dependencies

    - name: Build
      run: npm run build  # Or yarn build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 3.108.61.251
        username: ubuntu
        key: ${{ secrets.MYSECRETKEY }}

        script: |
          cd /home/ubuntu/projectusman
          git pull origin master  # Pull changes from the 'master' branch
          rm -rf *  # Remove all existing files in the project directory
          mv /home/ubuntu/projectusman* ./  # Move the contents of the 'build' directory to the project directory
          # pm2 restart react  # Restart your app using PM2 or another process manager
