name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code to server
        run: |
          ssh -i ${{ secrets.MYSECRETKEY }} ubuntu@3.108.61.251 "cd /home/ubuntu/autodep && git pull origin master"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
