name: My Deployment Workflow

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change to your desired Node.js version (e.g., Node.js 14)

    - name: Install dependencies
      run: npm ci --only=production  # Install production dependencies

    - name: Build
      run: npm run build  # Or yarn build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build  # Adjust this path to match the location of your build artifacts

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 3.108.61.251
        username: ubuntu
        key: ${{ secrets.MYSECRETKEY }}

        script: |
          cd /home/ubuntu/newfolder
          git pull origin main  # Pull changes from the 'main' branch (change if necessary)

          # Copy build artifacts from GitHub Actions workspace to the server directory
          cp -r $GITHUB_WORKSPACE/build/* ./home/ubuntu/myfold

          # Optionally, you can install production dependencies and restart your app here
