name: My first automation

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.6.0  # Change to your desired Node.js version

    - name: Install dependencies
      run: npm ci --only=production  # Install production dependencies

    - name: Build
      run: npm run build  # Or yarn build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 3.108.61.251
        username: ubuntu
        key: -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAIEAuffp5Y2QPnmIGKWJD6q3Dk4PazDZifuoOmw3Bq3gzoyrf+56x9Yf
          m5aUEOWoGJO7wE+SnsBrbk0zBbZD8LNWTFrygpbv3Owd4wnYstmMeAyUzZx9WLTEdCzz0i
          7p1D1W1NVDoPuYyPNRrP4eL93JjEE8qAY30yc/+SDmJcrxabkAAAIItoiqrLaIqqwAAAAH
          c3NoLXJzYQAAAIEAuffp5Y2QPnmIGKWJD6q3Dk4PazDZifuoOmw3Bq3gzoyrf+56x9Yfm5
          aUEOWoGJO7wE+SnsBrbk0zBbZD8LNWTFrygpbv3Owd4wnYstmMeAyUzZx9WLTEdCzz0i7p
          1D1W1NVDoPuYyPNRrP4eL93JjEE8qAY30yc/+SDmJcrxabkAAAADAQABAAAAgGH37XslyZ
          Bv+7doNT1QpODfVJYWhPOA5M3qRk65eQ22434gxwPRlJMlj1kbcyOHaEhWYxpIqg/QkYl3
          zHDYOSRX9pah30t4lQurCVslcoWPvOcgQAHz6JWbnvImlDCSd+7SG5vNfxFqbNnJ1KMuXk
          YFZ2EwZv6T0cMjP/B2d9LVAAAAQFZVPHDUf3CuWpTVBDwEhcQRmhLz7nhhROWfgzTlpWW9
          ob9MIBJapZrrnX+inpFemEdWEIuKg9WNd9hlmSNjHeoAAABBAOlvhYdOKktPMqGg+8H6W4
          2SdzXx+edkruudN/6g2gCDhjH0DScpSKxaSmI/fcknbm7E4F/vz2QO7SQOf+Py/XsAAABB
          AMvxyukasRvn713WKcexO02da+cWosK1HMWfq6tJ4YicCqpDSqa3VH0MfIiltFl6NsSwIP
          xvEbf+F4KmwZgRPVsAAAAObXVzbWFuc2hhbXNoYWQBAgMEBQ==
          -----END OPENSSH PRIVATE KEY-----
          

        script: |
          cd /home/ubuntu/projectusman
          git pull
          npm install --only=production  # Install production dependencies on the server
          pm2 restart your-app  # Restart your app using PM2 or another process manager
