name: Deploy Build to Server

on:
  push:
    branches:
      - master # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MYSECRETKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 13.126.221.51 >> ~/.ssh/known_hosts
        env:
          MYSECRETKEY: ${{ secrets.MYSECRETKEY }}

      - name: Deploy Build
        run: |
          # Copy the build artifacts to the server using SCP
          scp -r ./path/to/your/build/* ubuntu@13.126.221.51:/home/ubuntu/newworkflow
